#!/usr/bin/env sh

if [ "$(uname -s)" = "Darwin" ]; then
    SCRIPT_ABS_PATH=$(greadlink -f "$0")
else
    SCRIPT_ABS_PATH=$(readlink -f "$0")
fi
SCRIPT_ABS_DIR=$(dirname "$SCRIPT_ABS_PATH")

if [ "$#" -lt 1 ]; then
    echo "Pass in the source directory to scan"
    exit 1
fi

$SCRIPT_ABS_DIR/joern --run scan --src "$@"
