addSbtPlugin("com.github.gseitz" % "sbt-protobuf" % "0.6.5")
addSbtPlugin("com.geirsson" % "sbt-scalafmt" % "1.5.1")
addSbtPlugin("com.github.sbt" % "sbt-findbugs" % "2.0.0")
addSbtPlugin("org.foundweekends" % "sbt-bintray" % "0.5.4")
addSbtPlugin("com.typesafe.sbt"  % "sbt-native-packager"   % "1.3.5")
addSbtPlugin("io.shiftleft" % "sbt-ci-release-early" % "2.0.18")
addSbtPlugin("com.dwijnand" % "sbt-dynver" % "4.1.1")
