name: pr
on: pull_request
jobs:
  pr:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 1.11
    - name: Run tests
      run: |
        sbt test scalafmtCheck stage
        ./target/universal/stage/bin/batteries
