name: release
on:
  push:
    branches: [master, main]
    tags: ["*"]
jobs:
  release:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: olafurpg/setup-scala@v10
      - uses: actions/cache@v2
        with:
          path: |
            ~/.sbt
            ~/.coursier
          key: ${{ runner.os }}-sbt-${{ hashfiles('**/build.sbt') }}
      - run: sbt scalafmtCheck test stage
      - run: sbt ciReleaseTagNextVersion createDistribution
      - run: sha512sum ./querydb.zip > ./querydb.zip.sha512
      - run: ./install.sh
      - run: ./joern-scan --dump || echo "{}" > /tmp/querydb.json
      - run: cp /tmp/querydb.json .
      - name: Export ENV vars
        run:
          echo "LATEST_TAG=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.LATEST_TAG }}
          release_name: ${{ env.LATEST_TAG }}
          draft: false
          prerelease: false
      - name: Upload querydb.zip
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./querydb.zip
          asset_name: querydb.zip
          asset_content_type: application/zip
      - name: Upload querydb.zip.sha512
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./querydb.zip.sha512
          asset_name: querydb.zip.sha512
          asset_content_type: text/plain
      - name: Upload querydb.json
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./querydb.json
          asset_name: querydb.json
          asset_content_type: application/json
